"""empty message

Revision ID: f8a141873b6c
Revises: 99bd1e884161
Create Date: 2020-05-14 11:47:52.053911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a141873b6c'
down_revision = '99bd1e884161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ippname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipps_ippname'), 'ipps', ['ippname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipps_ippname'), table_name='ipps')
    op.drop_table('ipps')
    # ### end Alembic commands ###
